% CONVERT_ALIGNED_IMAGE Converts an image to a pair of grayscale vectors
% for use in forming the search matrix.  The two output vectors represent:
% 
%   (1) the image aligned to the 'aligned_shape'
%   (2) the image generated by sending (1) through the Combined Model
% 
% Created by Thomas R. Grieve
% 7 April 2012
% University of Utah
% 

function [updated_gray, offset_normalized] = convert_aligned_image(imgIn, aligned_shape, ObjectPixels, base_points, Triangles, shape_params, appearance_matrix, mean_appearance, combined_matrix, mean_combined, num_weights, options)

    % Extract inputs
    if (isfield(options,'debug_mode'))
        debug_mode = options.debug_mode;
    else
        debug_mode = false;
    end
    
    % Convert the image intensities using the offset vector
    gray_offset = convert_image_to_vector(imgIn, aligned_shape, ObjectPixels, base_points, Triangles, debug_mode);
    [offset_normalized, alpha, beta] = normalize_gray_levels(gray_offset);
    
    % Recombine the Shape and Gray-Level parameter vectors
    new_appearance_params = appearance_matrix' * (offset_normalized - mean_appearance);
    new_combined_params = [shape_params; new_appearance_params];
    
    % Calculate the Combined Model parameters
    new_model_params = combined_matrix' * (new_combined_params - mean_combined);
    
    % Convert to Gray-Level parameters
    updated_combined_params = mean_combined + combined_matrix * new_model_params;
    updated_appearance_params = updated_combined_params((num_weights+1):end);
    
    % Convert to an image
    updated_gray = mean_appearance + appearance_matrix * updated_appearance_params;

end % function